name: modular_foundation
description: A modular, declarative, and codegen-first architecture for scalable Flutter applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  fuzzy_bolt: ^2.0.2
  get_it: ^8.2.0
  logging: ^1.3.0
  memory_cache: ^1.2.0
  meta: ^1.17.0
  rxdart: ^0.28.0
dev_dependencies:
  build_runner: ^2.10.1
  custom_lint: ^0.8.1
  freezed: ^3.2.3
  freezed_lint: ^0.0.12
  lints: ^6.0.0
  modular_foundation_lints:
    path: ../modular_foundation_lints
  test: ^1.25.6
